image: docker:latest
stages:
  - container
  - deploy
container:
  stage: container
  script:
    - docker build -t subhomay/testnode .
deploy:
  stage: deploy
  script:
    - docker run -p 3000:3000 subhomay/testnode
    - docker image rm subhomay/testnode