language: node_js
node_js:
  - "stable"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
cache:
  directories:
    - "node_modules"